name: Terraform Apply
on: workflow_dispatch
env: 
  ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}

jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve 
